name: Manhunt
version: '${project.version}'
main: dan.plugin.manhunt.Manhunt
api-version: '1.20'

commands:
  startManhunt:
    description: Start the manhunt game
    usage: /<command>
  stopManhunt:
    description: Stops the manhunt game
    usage: /<command>
  addHunter:
    description: Adds a player to the hunter team
    usage: /<command> <playerName>
  removeHunter:
    description: Removes a player from the hunter team
    usage: /<command> <playerName>
  setRunner:
    description: Sets a player to be the runner
    usage: /<command> <playerName>
  removeRunner:
    description: Removes the runner
    usage: /<command>
  manhuntInfo:
    description: Outputs the current list of players included in the game
    usage: /<command>
  preventTeamOverlap:
    description: Enforces exclusivity between hunters and runner. Turned off by default
    usage: /<command> <true|false>
  test:
    description: Test scenario to go through the flow.
    usage: /<command>